config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get "movies", to: "movies#index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Autenticação
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  # Usuários
  get 'signup', to: 'users#new'
  get 'profile', to: 'users#profile'
  resources :users, only: [:create, :edit, :update]
  
  # Filmes
  resources :movies do
    # Comentários
    resources :comentarios, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comentario.rb
# app/models/comentario.rb
class Comentario < ApplicationRecord
  # belongs_to :user  # Removemos a associação obrigatória com User
  validates :conteudo, presence: true, length: { minimum: 2, maximum: 1000 }
  validates :author_name, presence: true, length: { minimum: 2, maximum: 50 }

  # Métodos para simular as associações
  def movie
    Movie.find_by(id: movie_id)
  end

  def user
    User.find_by(id: user_id) if user_id
  end

  def author_display_name
    user_id ? user.name : author_name
  end

  def anonymous?
    user_id.nil?
  end
end

app/models/movie.rb
# app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  
  validates :title, presence: true
  validates :release_year, numericality: { 
    only_integer: true, 
    greater_than: 1900, 
    less_than_or_equal_to: Date.today.year 
  }
  
  # MÉTODOS MANUAIS PARA COMENTÁRIOS
  def comentarios
    Comentario.where(movie_id: id).order(created_at: :desc)
  end
  
  def comentarios_count
    Comentario.where(movie_id: id).count
  end
  
  def build_comentario(attributes = {})
    Comentario.new(attributes.merge(movie_id: id))
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  
  has_many :movies, dependent: :destroy
  has_many :comentarios, dependent: :destroy
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validate :password_strength, on: :create
  
  private
  
  def password_strength
    return if password.blank?
    
    # Mínimo 6 caracteres
    if password.length < 6
      errors.add(:password, 'deve ter pelo menos 6 caracteres')
    end
    
    # Pelo menos uma letra e um número (opcional - pode remover se quiser mais simples)
    unless password =~ /[a-zA-Z]/ && password =~ /\d/
      errors.add(:password, 'deve conter letras e números')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  
  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'Por favor, faça login para acessar esta página.'
    end
  end
end

app/controllers/comentarios_controller.rb
# app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :require_login, only: [:destroy]  # Apenas destroy requer login
  
  def create
    @movie = Movie.find(params[:movie_id])
    @comentario = Comentario.new(comentario_params)
    @comentario.movie_id = @movie.id
    
    # Se o usuário estiver logado, associa ao usuário
    if logged_in?
      @comentario.user_id = current_user.id
      @comentario.author_name = current_user.name  # Preenche automaticamente
    end
    
    if @comentario.save
      redirect_to movie_path(@movie), notice: 'Comentário adicionado com sucesso!'
    else
      redirect_to movie_path(@movie), alert: "Erro ao adicionar comentário: #{@comentario.errors.full_messages.join(', ')}"
    end
  end
  
  def destroy
    @comentario = Comentario.find_by(id: params[:id])
    
    # Só permite excluir se for o autor do comentário ou se for dono do filme
    if @comentario && (current_user.id == @comentario.user_id || current_user.id == @comentario.movie.user_id)
      @movie = @comentario.movie
      @comentario.destroy
      redirect_to movie_path(@movie), notice: 'Comentário removido com sucesso!'
    else
      redirect_to movies_path, alert: 'Você não tem permissão para excluir este comentário.'
    end
  end
  
  private
  
  def comentario_params
    params.require(:comentario).permit(:conteudo, :author_name)
  end
end

app/controllers/movies_controller.rb
# app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  
  def index
    # Paginação - 6 filmes por página, ordenados por ano mais recente
    @movies = Movie.all.order(release_year: :desc, created_at: :desc).page(params[:page]).per(6)
  end
  
  def new
    @movie = current_user.movies.new
  end
  
  def create
    @movie = current_user.movies.new(movie_params)
    
    if @movie.save
      redirect_to movies_path, notice: 'Filme adicionado com sucesso!'
    else
      render :new
    end
  end
  
  def show
    @movie = Movie.find(params[:id])
  end
  
  def edit
    @movie = current_user.movies.find(params[:id])
  end
  
  def update
    @movie = current_user.movies.find(params[:id])
    
    if @movie.update(movie_params)
      redirect_to movies_path, notice: 'Filme atualizado com sucesso!'
    else
      render :edit
    end
  end
  
  def destroy
    @movie = current_user.movies.find(params[:id])
    @movie.destroy
    redirect_to movies_path, notice: 'Filme removido com sucesso!'
  end
  
  private
  
  def movie_params
    params.require(:movie).permit(:title, :description, :genre, :release_year, :diretor, :duracao, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to profile_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:email])
    
    
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Login realizado com sucesso!'
    else
      flash.now[:alert] = 'Email ou senha inválidos'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logout realizado com sucesso!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:profile, :edit, :update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Conta criada com sucesso!'
    else
      render :new
    end
  end

  def profile
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    
    
    update_params = user_params
    if update_params[:password].blank?
      update_params.delete(:password)
    end
    
    if @user.update(update_params)
      redirect_to profile_path, notice: 'Perfil atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def user_params
    
    params.require(:user).permit(:name, :email, :password)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'Por favor, faça login para acessar esta página.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "mFilmes", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Filmes", filmes_path, class: "nav-link" %>
        </li>
      </ul>
      
      <ul class="navbar-nav">
        <% if logged_in? %>
          <!-- Usuário logado -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Minha Conta", profile_path, class: "dropdown-item" %></li>
              <li><%= link_to "Editar Perfil", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sair", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <!-- Usuário deslogado -->
          <li class="nav-item">
            <%= link_to "Entrar", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cadastrar", signup_path, class: "nav-link btn btn-outline-primary ms-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MFilmes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <head>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS (via CDN) -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    >

    <!-- Bootstrap JS (via CDN) -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
      defer
    ></script>
  </head>

  <body class="bg-black text-white">
    <nav class="navbar navbar-expand-lg custom-navbar fixed-top navbar-dark">
  <div class="container-fluid">
    <%= link_to "🎬 M Filmes", root_path, class: "navbar-brand fw-bold text-success" %>

    <!-- Botão hambúrguer -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Itens da navbar -->
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if logged_in? %>    
         
          <li class="nav-item">
            <%= link_to "➕ Adicionar Filme", new_movie_path, class: "nav-link text-success" %>
          </li>
           <%= link_to "👤 Editar Conta", edit_user_path(current_user), class: "btn btn-black text-success bg-black" %>
          <li class="nav-item">
            <%= link_to "🚪 Sair", logout_path, method: :delete, class: "nav-link text-danger" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "🔑 Login", login_path, class: "nav-link text-success" %>
          </li>
          <li class="nav-item">
            <%= link_to "📝 Cadastrar", signup_path, class: "nav-link text-success" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


    <!-- Conteúdo com padding no topo -->
    <div class="container mt-5 pt-4">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      <% end %>
      
      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
    
<ul class="navbar-nav me-auto">
  <li class="nav-item">
    <%= link_to '', movies_path, class: 'nav-link text-success fw-semibold' %>
  </li>
</ul>
<ul class="navbar-nav me-auto">
  <%= link_to "Adicionar um Filme", new_movie_path, class: "btn btn-success mt-3" %>
        
</ul>
  </body>
</html>

app/views/movies/edit.html.erb
<!-- app/views/movies/edit.html.erb -->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card bg-dark text-white border-success">
        <div class="card-header bg-success text-dark">
          <h2 class="text-center mb-0">✏️ Editar Filme</h2>
        </div>
        <div class="card-body">
          <%= form_with model: @movie, local: true do |form| %>
            <% if @movie.errors.any? %>
              <div class="alert alert-danger">
                <h5>Corrija os seguintes erros:</h5>
                <ul class="mb-0">
                  <% @movie.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="mb-3">
              <%= form.label :title, "Título do Filme", class: "form-label text-success fw-semibold" %>
              <%= form.text_field :title, class: "form-control bg-black text-white border-success", required: true %>
            </div>

            <div class="mb-3">
              <%= form.label :diretor, "Diretor", class: "form-label text-success fw-semibold" %>
              <%= form.text_field :diretor, class: "form-control bg-black text-white border-success" %>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                  <%= form.label :genre, "Gênero", class: "form-label text-success fw-semibold" %>
                  <%= form.text_field :genre, class: "form-control bg-black text-white border-success" %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <%= form.label :duracao, "Duração", class: "form-label text-success fw-semibold" %>
                    <%= form.text_field :duracao, 
                          class: "form-control bg-black text-white border-success", 
                          placeholder: "Ex: 2h28m",
                          pattern: "[0-9]{1,3}h[0-9]{1,2}m",
                          title: "Formato: 2h28m (horas e minutos)",
                          id: "duracao_field" %>
                      <small class="form-text text-muted">Formato: 2h28m (horas e minutos)</small>
                </div>
              </div>
            </div>

            <div class="mb-3">
              <%= form.label :release_year, "Ano de Lançamento", class: "form-label text-success fw-semibold" %>
              <%= form.number_field :release_year, class: "form-control bg-black text-white border-success", min: "1900", max: "2024" %>
            </div>

            <div class="mb-3">
              <%= form.label :description, "Descrição", class: "form-label text-success fw-semibold" %>
              <%= form.text_area :description, class: "form-control bg-black text-white border-success", rows: 4 %>
            </div>

            <div class="mb-3">
              <%= form.label :image, "Capa do Filme", class: "form-label text-success fw-semibold" %>
              
              <% if @movie.image.attached? %>
                <div class="mb-2">
                  <p class="text-success">Imagem atual:</p>
                  <%= image_tag @movie.image, class: "img-thumbnail", style: "max-height: 150px;", alt: @movie.title %>
                </div>
              <% end %>
              
              <%= form.file_field :image, class: "form-control bg-black text-white border-success", accept: "image/*" %>
              <small class="form-text text-muted">Deixe em branco para manter a imagem atual</small>
            </div>

            <div class="d-grid gap-2">
              <%= form.submit "💾 Atualizar Filme", class: "btn btn-success" %>
              <%= link_to "❌ Cancelar", movies_path, class: "btn btn-outline-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<!-- app/views/movies/index.html.erb -->
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="text-success">🎬 Meus Filmes</h2>
    <% if logged_in? %>
      <%= link_to "➕ Adicionar Filme", new_movie_path, class: "btn btn-success" %>
    <% end %>
  </div>

  <% if @movies.empty? %>
    <div class="card bg-dark text-white border-success">
      <div class="card-body text-center py-5">
        <h4 class="text-muted">Nenhum filme cadastrado ainda</h4>
        <% if logged_in? %>
          <p class="text-muted">Seja o primeiro a adicionar um filme!</p>
          <%= link_to "Adicionar Primeiro Filme", new_movie_path, class: "btn btn-success mt-3" %>
        <% else %>
          <p class="text-muted">Faça login para adicionar filmes</p>
          <%= link_to "Fazer Login", login_path, class: "btn btn-success mt-3" %>
        <% end %>
      </div>
    </div>
  <% else %>
    <!-- Lista Vertical - Um filme por linha em todos os dispositivos -->
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-12 col-md-6 col-lg-4 mb-4">
          <div class="card bg-dark text-white border-success h-100 movie-card-mobile">
            <div class="row g-0">
              <!-- Imagem do Filme -->
              <div class="col-md-3 movie-image-container">
                <% if movie.image.attached? %>
                  <%= image_tag movie.image, class: "img-fluid w-100 h-100 movie-image", alt: movie.title %>
                <% else %>
                 <div class="movie-placeholder d-flex align-items-center justify-content-center">
                    <span class="fs-1 text-muted">🎬</span>
                 </div>
                <% end %>
              </div>

              
              <!-- Conteúdo do Filme -->
              <div class="col-md-9">
                <div class="card-body">
                  <div class="d-flex justify-content-between align-items-start mb-3">
                    <h5 class="card-title text-success mb-0"><%= movie.title %></h5>
                    <div class="d-flex align-items-center gap-2">
                      <span class="badge bg-success"><%= movie.release_year %></span>
                      <small class="text-light">💬 <%= movie.comentarios_count %></small>
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-sm-6">
                      <p class="card-text mb-1">
                        <small class="text-success">Diretor:</small><br>
                        <span class="text-light"><%= movie.diretor || "Não informado" %></span>
                      </p>
                      <p class="card-text mb-1">
                        <small class="text-success">Gênero:</small><br>
                        <span class="text-light"><%= movie.genre || "Não especificado" %></span>
                      </p>
                    </div>
                    <div class="col-sm-6">
                      <p class="card-text mb-1">
                        <small class="text-success">Duração:</small><br>
                        <span class="text-light"><%= movie.duracao || "Não informada" %></span>
                      </p>
                      <p class="card-text mb-1">
                        <small class="text-success">Adicionado por:</small><br>
                        <span class="text-warning"><%= movie.user.name %></span>
                      </p>
                    </div>
                  </div>
                  
                  <% if movie.description.present? %>
                    <p class="card-text mt-2">
                      <small class="text-success">Descrição:</small><br>
                      <span class="text-light"><%= truncate(movie.description, length: 150) %></span>
                    </p>
                  <% end %>
                  
                  <div class="mt-3">
                    <div class="d-flex flex-wrap gap-2">
                      <%= link_to "👀 Ver Detalhes", movie_path(movie), class: "btn btn-outline-info btn-sm" %>
                      <% if logged_in? && current_user == movie.user %>
                        <%= link_to "✏️ Editar", edit_movie_path(movie), class: "btn btn-outline-warning btn-sm" %>
                        <%= button_to "🗑️ Excluir", movie_path(movie), method: :delete, 
                            class: "btn btn-outline-danger btn-sm",
                            data: { confirm: "Tem certeza que deseja excluir #{movie.title}?" } %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    
    <!-- Paginação -->
    <!-- Paginação com classe personalizada -->
<div class="d-flex justify-content-center mt-4">
  <nav>
    <ul class="pagination pagination-custom">
      <% if @movies.current_page > 1 %>
        <li class="page-item">
          <%= link_to "‹", url_for(page: @movies.current_page - 1), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item disabled">
          <span class="page-link">‹</span>
        </li>
      <% end %>
      
      <% (@movies.current_page-2..@movies.current_page+2).each do |page| %>
        <% if page > 0 && page <= @movies.total_pages %>
          <li class="page-item <%= 'active' if page == @movies.current_page %>">
            <%= link_to page, url_for(page: page), class: "page-link" %>
          </li>
        <% end %>
      <% end %>
      
      <% if @movies.current_page < @movies.total_pages %>
        <li class="page-item">
          <%= link_to "›", url_for(page: @movies.current_page + 1), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item disabled">
          <span class="page-link">›</span>
        </li>
      <% end %>
    </ul>
  </nav>
</div>
  <% end %>
</div>

app/views/movies/new.html.erb
<!-- app/views/movies/new.html.erb -->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card bg-dark text-white border-success">
        <div class="card-header bg-success text-dark">
          <h2 class="text-center mb-0">🎬 Adicionar Novo Filme</h2>
        </div>
        <div class="card-body">
          <%= form_with model: @movie, local: true do |form| %>
            <% if @movie.errors.any? %>
              <div class="alert alert-danger">
                <h5>Corrija os seguintes erros:</h5>
                <ul class="mb-0">
                  <% @movie.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="mb-3">
              <%= form.label :title, "Título do Filme", class: "form-label text-success fw-semibold" %>
              <%= form.text_field :title, class: "form-control bg-black text-white border-success", required: true, placeholder: "Ex: O Poderoso Chefão" %>
            </div>

            <div class="mb-3">
              <%= form.label :diretor, "Diretor", class: "form-label text-success fw-semibold" %>
              <%= form.text_field :diretor, class: "form-control bg-black text-white border-success", placeholder: "Ex: Christopher Nolan" %>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                  <%= form.label :genre, "Gênero", class: "form-label text-success fw-semibold" %>
                  <%= form.text_field :genre, class: "form-control bg-black text-white border-success", placeholder: "Ex: Drama, Ação, Comédia" %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <%= form.label :duracao, "Duração", class: "form-label text-success fw-semibold" %>
                    <%= form.text_field :duracao, 
                          class: "form-control bg-black text-white border-success", 
                          placeholder: "Ex: 2h28m",
                          pattern: "[0-9]{1,3}h[0-9]{1,2}m",
                          title: "Formato: 2h28m (horas e minutos)",
                          id: "duracao_field" %>
                      <small class="form-text text-muted">Formato: 2h28m (horas e minutos)</small>
                </div>
              </div>
            </div>

            <div class="mb-3">
              <%= form.label :release_year, "Ano de Lançamento", class: "form-label text-success fw-semibold" %>
              <%= form.number_field :release_year, class: "form-control bg-black text-white border-success", min: "1900", max: "2024", placeholder: "Ex: 1994" %>
            </div>

            <div class="mb-3">
              <%= form.label :description, "Descrição", class: "form-label text-success fw-semibold" %>
              <%= form.text_area :description, class: "form-control bg-black text-white border-success", rows: 4, placeholder: "Descreva o filme..." %>
            </div>

            <div class="mb-3">
              <%= form.label :image, "Capa do Filme", class: "form-label text-success fw-semibold" %>
              <%= form.file_field :image, class: "form-control bg-black text-white border-success", accept: "image/*" %>
              <small class="form-text text-muted">Formatos: JPG, PNG, GIF. Tamanho máximo: 5MB</small>
            </div>

            <div class="d-grid gap-2">
              <%= form.submit "🎬 Adicionar Filme", class: "btn btn-success btn-lg" %>
              <%= link_to "↩️ Cancelar", movies_path, class: "btn btn-outline-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<div class="row justify-content-center mt-4">
  <div class="col-md-6">
    <div class="card bg-dark text-white border-success">
      <div class="card-header bg-success text-dark">
        <h2 class="text-center mb-0">✏️ Editar Perfil</h2>
      </div>
      <div class="card-body">
        <%= form_with model: @user, local: true do |form| %>
          <div class="mb-3">
            <%= form.label :name, "Nome", class: "form-label text-success fw-semibold" %>
            <%= form.text_field :name, class: "form-control bg-black text-white border-success", required: true %>
          </div>
          
          <div class="mb-3">
            <%= form.label :email, "Email", class: "form-label text-success fw-semibold" %>
            <%= form.email_field :email, class: "form-control bg-black text-white border-success", required: true %>
          </div>
          
          <div class="mb-3">
            <%= form.label :password, "Nova Senha", class: "form-label text-success fw-semibold" %>
            <%= form.password_field :password, class: "form-control bg-black text-white border-success", placeholder: "Deixe em branco para manter a atual" %>
            <div class="form-text text-muted">
              <small>Deixe em branco se não quiser alterar a senha</small>
            </div>
          </div>
          
          <div class="d-grid gap-2">
            <%= form.submit "💾 Atualizar Perfil", class: "btn btn-success" %>
            <%= link_to "❌ Cancelar", profile_path, class: "btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-md-8">
    <h2 class="text-success mb-4">👤 Minha Conta</h2>
    
    <div class="card bg-dark text-white border-success">
      <div class="card-header bg-success text-dark">
        <h5 class="mb-0">Informações do Perfil</h5>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <p><strong class="text-success">Nome:</strong> <%= current_user.name %></p>
          </div>
          <div class="col-md-6">
            <p><strong class="text-success">Email:</strong> <%= current_user.email %></p>
          </div>
        </div>
        
        <div class="mt-4">
          <%= link_to "✏️ Editar Perfil", edit_user_path(current_user), class: "btn btn-success me-2" %>
          <%= link_to "📋 Voltar para Filmes", movies_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>